-- Active: 1738296726605@@192.168.100.9@5432@chatapp
CREATE TABLE public.users (
    user_id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    picture text,
    is_email_verified boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_login_at timestamp with time zone,
    PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_name ON public.users USING btree (name);

CREATE TABLE public.verification_tokens (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME verification_tokens_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    token text,
    verify_code character varying(6),
    user_id character varying(36),
    token_type character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean DEFAULT false,
    PRIMARY KEY (id),
    CONSTRAINT verification_tokens_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_verification_tokens_token ON public.verification_tokens USING btree (token);
CREATE INDEX idx_verification_token_lookup ON public.verification_tokens USING btree (token, verify_code, is_used, expires_at);

CREATE TABLE public.sessions (
    session_id VARCHAR(50) PRIMARY KEY,
    user_id character varying(36),
    access_token text NOT NULL,
    refresh_token text NOT NULL,
    device_info character varying(255),
    ip_address character varying(45),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone NOT NULL,
    last_activity_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) ON DELETE CASCADE
);

ALTER TABLE sessions ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_sessions_token ON public.sessions USING btree (access_token);
CREATE INDEX idx_sessions_user_id ON public.sessions USING btree (user_id);


